### ISSUE TITLE
[Feature Request] please add unifi-controller and frontail

### ISSUE THREAD

**Issue by Schnuecks** [SensorsIot/IOTstack#164] opened 2020-11-01 20:45 UTC
This would be a nice enhancement for several users.
Found here: https://github.com/linuxserver/docker-unifi-controller

another suggestion would be nice for openhab users, they often use frontail as a webbased logviewer
Found here: https://github.com/mthenw/frontail

**Comment by mats-nk** [comment] 2020-11-02 08:35
You can get started by testing it your self. `compose-override.yml` is a file you can create in the root and add your content into it.

I have been tinkering around with a NGINX and then I just added to `compose-override.yml`:

`services:
  web:
    image: nginx
    volumes:
      - ./volumes/nginx:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - iotstack_nw`

Then just run `./menu.sh` and rebuild the IOTstack again.

**Comment by Schnuecks** [comment] 2020-11-02 10:13
Ok, hi thanks for the reply. This is clarifying why my "docker-compose.override.yml" isn't working as expected. The normal docker-way is docker-compose.override.yml beside the docker-compose.yml. I will try it with the compose.override.yml. Actually i edited the docker-compose.yml and integrated it by hand. I think it would be gone if i run menu.sh to rebuild. Ok, found it in the documentation.

**Comment by mats-nk** [comment] 2020-11-03 10:32
Iv `docker-compose.override.yml ` is the standard, please consider posting a change request so IOTstack is following standards/common practice.

**Comment by lichtteil** [comment] 2020-12-22 15:13
I managed to add the Unifi controller.
In your IOTstack folder create a `compose-override.yml` and add the content from here: https://gist.github.com/lichtteil/83b9f4a733e4ca17e2b25789b3dda3f0

Use `menu.sh` to build your stack again (to include the overwrites to your docker-compose file) and start the container `docker-compose up -d`.

**Comment by ukkopahis** [comment] 2022-06-24 07:13
Duplicate of #98 Add Ubiquiti UniFi controller support.

**Closed** 2022-09-11 05:48 UTC
